version: 3.8
services:
  app:
    build: ./
    image: app
    command: npm run start.dev
    volumes:
      - "./app:/src/app"
    ports:
      - "8080:8080"
    networks:
      dev:
        aliases:
          - app.dev
    depends_on:
      - db
  db:
    image: postgres
    environment:
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_DB=models
        - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

networks:
  net:
    dev:
      external:
        name: dev
